server:
  http_listen_port: 9999
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.1.x:3100/loki/api/v1/push
scrape_configs: 
  - job_name: my_Server_Genaral_logs
    static_configs:
    - targets:
      - localhost
      labels:
        job: my_Server_Genaral_logs
        __path__: /var/log/*log
  - job_name: my-Server_Utimaco_batt
    static_configs:
    - targets:
      - localhost
      labels:
        job: my_Server_Utimaco_batt
        __path__: /home/batstatus.txt
